version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-veterinaria
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock # 👈 acceso a Docker del host
    #command: sleep infinity
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    image: mysql:8.0
    container_name: mysql-veterinaria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: veterinaria
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - default
